import { asset } from './asset.js';

// Featured Summit speakers.
export const speakers = [
  {
    name: 'Marianta Njomia',
    title: 'President of Ambazonia',
    role: 'Keynote Speaker',
    region: '',
    images: [asset('/images/marianta-njomia.jpg')],
    objectPosition: 'center 8%',
    bio: [
      'Her Excellency Marianta Njomia serves as President of the Interim Government of Ambazonia, carrying the hopes of the peoples of the Anglophone regions of the former Southern Cameroons. A stateswoman who leads in exile, she has become a steadfast voice for self-determination, dignity and human rights — bearing her people’s cause onto the international stage with resolve and grace.',
    ],
  },
  {
    name: 'Aja Brown',
    title: 'Former Mayor of Compton, California',
    role: 'Author of “Visionary Builders” · Strategic Impact Partner, FORWARD',
    region: 'Diaspora · Compton, USA',
    images: [asset('/images/aja-brown.jpg')],
    bio: [
      'Aja Brown is a transformative leader and two-term Mayor of Compton — one of the youngest mayors in America to lead a major city. She turned vision into results, driving over $3 billion in new investment into her city and a reduction of roughly 60% in violent crime, while breaking a glass ceiling and inspiring a new wave of women mayors across the nation.',
      'She launched the Compton Pledge — the largest guaranteed basic income programme in the country at the time — and was a founding mayor of Mayors for a Guaranteed Income. A multi-founder and co-founder of Omega Circle Holdings, she now partners with governments nationwide through FORWARD to modernise public systems, and is the author of “Visionary Builders”.',
    ],
  },
  {
    name: 'Prince Iganda Kamole',
    title: 'Prince of the Bashinjahavu-Bashaho',
    role: 'President, Movement for the Cultural Renaissance of Africa',
    region: 'DR Congo',
    images: [asset('/images/prince-iganda-1.jpg'), asset('/images/prince-iganda-2.jpg')],
    bio: [
      "Prince Iganda Kamole descends from two royal families of Kivu, in the east of the Democratic Republic of the Congo — the N'Iganda of the Bashinjahavu-Bashaho on his father's side, and the Katana of the Banyamocha, who reign at Irhambi-Katana, on his mother's side.",
      'In 2021, under divine inspiration, the sub-clan chiefs and custodians of custom across Kalehe, Kabare, Idjwi, Walungu, Mwenga and Masisi designated him as representative of the Bashinjahavu-Bashaho — a community of more than one million members, which he has coordinated ever since.',
      'He is President of the Movement for the Cultural Renaissance of Africa, championing African unity and a shared consciousness of belonging in the service of peace and development, and a representative of the National Alliance of Traditional Authorities of the Congo. A jurist and political scientist, he holds a Bachelor of Laws and a Master of Political Science in International Relations from the Université Libre de Bruxelles.',
    ],
  },
  {
    name: 'Olori Afolashade Ashley Ogunwusi',
    title: 'Queen (Olori) of Ife',
    role: 'Yeye Omi Oodua · Chartered Accountant & Entrepreneur',
    region: 'Diaspora · England',
    images: [asset('/images/olori-ashley.jpg')],
    objectPosition: 'center 35%',
    bio: [
      'Olori Afolashade Ashley Ogunwusi (née Adegoke) is a spouse of the Ooni of Ife, His Imperial Majesty Oba Adeyeye Enitan Ogunwusi, Ojaja II. She holds the title of Yeye Omi Oodua — “Mother of Oodua’s Water”.',
      "A chartered accountant and entrepreneur based between Nigeria and the United Kingdom, she holds a Master's degree in Accounting and Finance from the University of Greenwich, and is the founder of the Ashley Adegoke Foundation, which supports underprivileged children and widows.",
    ],
  },
  {
    name: 'Dr Gia Grant-Rutledge',
    title: 'Chief Strategy Officer, The Kingdom Collective Group',
    role: 'Chief Strategy & Partnerships Officer · Africa–USA International Chamber of Commerce & Industry · PAGTIC',
    region: 'Diaspora · California, USA',
    images: [asset('/images/gia-grant-rutledge.jpg')],
    objectPosition: 'center 20%',
    bio: [
      'Dr Gia Grant-Rutledge is Chief Strategy Officer of The Kingdom Collective Group and Chief Strategy & Partnerships Officer of the Africa–USA International Chamber of Commerce & Industry and PAGTIC. Her work connects Africa, the United States, and the Pan-African Diaspora through international trade, investment, and commerce.',
      'She champions strategic partnerships to advance transformative trade and investment, accelerate infrastructure development, and expand economic opportunity across Africa and the global Pan-African Diaspora.',
    ],
  },
  {
    name: 'Queen Mother Manal Omar Al-Ansi',
    title: 'Enstooled as Naa Afoley Jormo',
    role: 'Attorney · Founder, Diaspora District & Global Diaspora Day',
    region: 'Diaspora · Atlanta, USA',
    images: [asset('/images/manal-al-ansi.jpg'), asset('/images/manal-al-ansi-2.jpg')],
    objectPosition: 'center 18%',
    insetPosition: 'center 10%',
    insetRound: true,
    bio: [
      'Born in Ethiopia, raised in the United States, and enstooled in Ghana as Queen Mother Naa Afoley Jormo, Manal Omar Al-Ansi is an attorney and strategic-partnerships consultant, and the founder of Diaspora District — a global hub for collaboration across the African diaspora.',
      'Her work is the quiet architecture of connection: developing leaders, building institutions, and turning relationships between government, industry, and education into partnerships of lasting consequence. Founder of Global Diaspora Day — a movement now recognised across three countries and two U.S. states — she champions a leadership that is collective in spirit, strategic in method, and generational in its reach.',
    ],
  },
  {
    name: 'Coralita Yard',
    title: 'Founder & CEO, Korvana',
    role: 'International Development Advocate · VP Caribbean, IPADA Initiative (Motherland Beckons)',
    region: 'Diaspora · Barbados, Caribbean',
    images: [asset('/images/coralita-yard.jpg')],
    objectPosition: 'center 12%',
    bio: [
      'Coralita Yard is an entrepreneur, humanitarian leader and international-development advocate, and the Founder and Chief Executive of Korvana — a venture dedicated to building enduring bridges between Africa and the Caribbean through business, culture, tourism and shared enterprise.',
      'She serves as Vice-President for the Caribbean of the IPADA Initiative (Motherland Beckons), reconnecting the diaspora with the continent, and as Special Adviser on Humanitarian Affairs within the Office of the Special Envoy for West Africa. A consultant, speaker and steadfast champion of women, youth and underserved communities, she has become a trusted voice in Pan-African cooperation and diaspora engagement — persuaded, above all, that collaboration is the surest architecture of lasting change.',
    ],
  },
  {
    name: 'Her Excellency Nyakan June',
    title: 'Global CEO, Timeless Women of Wonder Africa',
    role: 'Strategy, Transformation & Innovation Expert · Founder, TWOW Africa · Chair, Global Innovation Society of Kenya',
    region: 'Kenya',
    images: [asset('/images/nyakan-june.jpg')],
    objectPosition: 'center 18%',
    bio: [
      'Her Excellency Nyakan June is a strategy, transformation and innovation expert whose twenty-seven-year career has been devoted to raising impact, efficiency, productivity and wealth across both the private and public sectors. She is the Global Chief Executive of Timeless Dynamic Services Ltd and the founder and Global CEO of Timeless Women of Wonder (TWOW) Africa — a movement celebrating and elevating the continent’s women of enduring influence.',
      'Chair of the Global Innovation Society of Kenya and of Group 7 Investments Company, an adviser to governments and a member of the Leadership, Ethics & Values Africa platform, she has been honoured as a Pan-African American Leadership Impact Award winner (2025) for Blazing the Trail, Chairman of the Year (2015) and a CIO Award winner (2012). She hosts the Accelerate Africa’s Growth Conferences — building on the legacy of her Timeless Women Conferences — and co-hosted the inaugural Africa Funding Tour in 2020, which supported 744 SMEs across six African countries through the pandemic. In 2022 she stood as an independent presidential aspirant in Kenya’s elections: a leader defined by service, courage, and the conviction that Africa’s growth is timeless.',
    ],
  },
  {
    name: 'Otunba (Dr.) Olawanle Raphael Akinboboye',
    title: 'Founder & President, La Campagne Tropicana Beach Resort',
    role: 'Keynote Speaker · Pan-African Tourism Icon · Founder, Motherland Beckons & IPADA',
    region: 'Nigeria',
    images: [asset('/images/akinboboye.jpg')],
    objectPosition: 'center 20%',
    bio: [
      'Otunba (Dr.) Olawanle Raphael Akinboboye is a Pan-African visionary, tourism icon and cultural entrepreneur — one of the continent’s foremost champions of heritage tourism, devoted to repositioning Africa as a leading destination for culture, investment and international engagement. As Founder and President of La Campagne Tropicana Beach Resort, he pioneered the world’s first authentic African-themed beach, forest and mangrove resort: a globally acclaimed model uniting indigenous architecture, environmental sustainability, luxury hospitality and African cultural identity. He holds a Master’s in Hospitality Management from Florida International University and an Honorary Doctorate for his contributions to tourism, culture and national development.',
      'He is the visionary founder of Motherland Beckons and IPADA — Pan-African movements reconnecting Africans and the Diaspora with their ancestral homeland through tourism, culture, commerce and investment, and inspiring thousands worldwide to rediscover the continent. An entrepreneur, author, strategist and cultural diplomat, he has advised governments, traditional institutions and international organisations on tourism development, destination branding and cultural diplomacy — an enduring voice of the African Renaissance, building lasting bridges between Africa and its worldwide family.',
    ],
  },
  {
    name: 'HRM Oba (Dr.) Olusegun Idowu Aderemi, JP',
    title: 'Atayero II of Aramoko-Ekiti Kingdom',
    role: 'Traditional Ruler · Entrepreneur · Regional President, Occupational Health & Safety (UK), Nigeria',
    region: 'Nigeria · Ekiti State',
    images: [asset('/images/oba-aderemi.jpg')],
    objectPosition: 'center 16%',
    bio: [
      'HRM Oba (Dr.) Amb. Olusegun Idowu Aderemi, JP, reigns as the Atayero II of Aramoko-Ekiti Kingdom in Ekiti State, ascending the throne of the Arakale Ruling House in January 2020 as son of Oba Okunola Osefaja Ajibike, Atayero I. A devout Christian and church elder who upholds the traditional customs of his forefathers, he is a dedicated custodian of Aramoko’s cultural heritage. He holds an MBA in Cultural Heritage Management, serves on the Governing Council of Lagos Business School, and is a Justice of the Peace and Fellow of numerous professional bodies.',
      'A renowned entrepreneur and employer of labour, he founded Segmat Springs Ltd in 1996 and built a group of auto-care enterprises — among them Automatic Fit and Energy Ltd, distributor for Michelin in Nigeria and partner to Total and NNPC — and, in 2021, the mobile venture Fixit and Go. As Nigeria’s Regional President of Occupational Health and Safety (UK) he is a leading advocate for road safety, and his philanthropy and peacebuilding have drawn recognition at home and abroad, including honours from the Mayors of Newark and Franklin, New Jersey. He is celebrated as a builder, motivator and symbol of African culture and tradition.',
    ],
  },
  {
    name: 'Princess Boitumelo Monoketsi',
    title: 'Chair, Foundation of African Royals',
    role: 'Educationist · Developmental Activist',
    region: 'South Africa',
    images: [asset('/images/boitumelo-monoketsi.jpg'), asset('/images/boitumelo-monoketsi-2.jpg')],
    objectPosition: 'center 12%',
    insetPosition: 'center 22%',
    insetRound: true,
    bio: [
      'Princess Boitumelo Monoketsi is an educationist and developmental activist who chairs the Foundation of African Royals. Her leadership rests upon a single, unifying imperative — continental unity — and the conviction that Africa’s modern socio-economic systems must be anchored in the historical wisdom of its traditional leaders. Rather than regarding traditional monarchies as symbolic or relics of the past, she draws them together as a living force for progress.',
      'Under her stewardship, the Foundation ensures that local communities are placed at the heart of socio-political decision-making — directed toward rural economic transformation and the skilling of Africa’s youth. In partnership with broader institutional bodies, it works to streamline traditional leadership into a formidable Pan-African entity, convening landmark continental gatherings and high-profile summits for traditional leaders across Africa and around the world.',
    ],
  },
  {
    name: 'HRM Professor Queen Eunice Bakare',
    title: 'Crown Queen of the Ikpai Clan, Cross River',
    role: 'Professor of Christian Education & Divinity · Founding President, Mothers on Planet Earth International',
    region: 'Cross River · Nigeria',
    images: [asset('/images/eunice-bakare.jpg')],
    objectPosition: 'center 8%',
    bio: [
      'Her Royal Majesty, Professor Queen Eunice Bakare (née Okey) is Crown Queen of the Ikpai Clan in Akamkpa, Cross River State, Nigeria — a monarch whose reign is inseparable from a lifetime of scholarship and faith. A Professor of Christian Education and Divinity and a professional marketer holding a PhD in Marketing, she is a teacher, preacher, author, and spiritual and motivational speaker, uniting the disciplines of the academy with the callings of the pulpit.',
      'She is Founder, Monarch and Presiding Priest of the New Jerusalem Empire International Organization, and Director of its Bible, Leadership and Professional Institute. As Founding President of Mothers on Planet Earth International and host of JAKAs, she has devoted her life’s work to faith, leadership, education, marriage enrichment and humanitarian service — with a particular and tender commitment to the empowerment and wellbeing of women, children and the less privileged across Nigeria, Africa and beyond. She makes her home in Abuja, Nigeria.',
    ],
  },
  {
    name: 'Queen Consort Maangela Imwiko',
    title: 'Queen Consort · Barotse Royal Establishment',
    role: 'Mwandi Palace · Western Province, Zambia',
    region: 'Zambia',
    images: [asset('/images/maangela-imwiko.jpg')],
    objectPosition: 'center 6%',
    bio: [
      'Queen Consort Maangela Imwiko is a royal matriarch of the Barotse Royal Establishment at Mwandi Palace, in the Western Province of Zambia — the ancestral heartland of the Lozi people. As Queen Consort she stands among the custodians of one of Southern Africa’s oldest and most revered monarchies, upholding the traditions, dignity and cultural inheritance of the Barotse nation.',
      'Robed in the resplendent regalia of Barotseland, she carries the living heritage of her people onto the international stage. Her presence at the African Global Queens Summit lends the gathering the grace, gravitas and timeless dignity of one of the continent’s most storied royal houses.',
    ],
  },
  {
    name: 'Dr Dianne Regisford',
    title: 'Founder, Evoking Belonging',
    role: 'Oxford City Councillor for Holywell · Belonging Futurist & Cultural Convener',
    region: 'Diaspora · United Kingdom',
    images: [asset('/images/dianne-regisford.jpg')],
    objectPosition: 'center 12%',
    bio: [
      'Dr Dianne Regisford is the visionary Founder of Evoking Belonging — a global living practice, philosophy and movement shaping the futures of the African-Caribbean Diaspora. Through its guiding triad of Culture, Polity and ARTivism, she cultivates an Indigenous Diaspora ecology of knowledge-making: an art of encounter, witness, enquiry, embodiment and cultural stewardship. A social-impact entrepreneur of more than thirty-five years, she is building cultural infrastructure across the Black Atlantic through a tri-continental process spanning Africa, the United Kingdom and the Caribbean.',
      'An Oxford City Councillor for Holywell, she is the first Black person elected as a Green Party councillor in Oxfordshire, and her civic leadership brings cultural justice, belonging and historically excluded knowledge into public life — ensuring governance shaped by lived experience as much as by institution. A Belonging Futurist, systems-change thinker, keynote speaker, writer and poet, she convenes leaders, artists, scholars and communities into “Evocative Enquiries” that turn complexity and difference into shared vision and collective action.',
      'The first Black scholar in the world to earn a PhD in Social Sculpture, Dr Regisford has pioneered an Ubuntu-centred approach that positions belonging itself as a transformative force for Diaspora leadership, governance and renewal. In September 2026 she launches UbuntuSphere — Evoking Belonging’s participatory space for living knowledge, collective imagination and globally connected enquiry.',
    ],
  },
  {
    name: 'Dr Elizabeth Kangethe',
    title: 'Vice-President, London Mayors Association',
    role: 'Past Mayor & Councillor, London Borough of Barking and Dagenham',
    region: 'Diaspora · London, United Kingdom',
    images: [asset('/images/elizabeth-kangethe.jpg'), asset('/images/elizabeth-kangethe-2.jpg')],
    objectPosition: 'center 12%',
    insetPosition: 'center 20%',
    insetRound: true,
    bio: [
      'Dr Elizabeth Kangethe is a distinguished civic leader and a past Mayor and Councillor of the London Borough of Barking and Dagenham. A Kenyan-British stateswoman based in London, she serves today as Vice-President of the London Mayors Association, championing civic leadership, community cohesion and the empowerment of women across the capital and beyond.',
      'Through decades of public service she has become a respected voice for inclusive local governance and diaspora leadership, building bridges between her Kenyan heritage and her adopted city of London — and carrying that same spirit of service to the African Global Queens Summit.',
    ],
  },
  {
    name: 'Dh. Lawrence Ellis',
    title: 'Founder & CEO, One Thriving Planet',
    role: 'Programme Host, Oxford · Climate, Biodiversity & Economic Inclusion',
    region: 'Diaspora · California, USA',
    images: [asset('/images/lawrence-ellis.jpg')],
    bio: [
      'Dhammācariya Lawrence Ellis is Founder and CEO of One Thriving Planet, a global consortium addressing three pressing crises — climate change, biodiversity loss and economic exclusion in the low-carbon transition. Its investment arm deploys some US $100 million a year toward the UN Sustainable Development Goals, while its Solutions arm runs initiatives on four continents, with members honoured by the Nobel Sustainability Award and the CANEX Prize across Africa.',
      'Drawing on his African and Native American heritage and Asian Earth-based traditions, he teaches an “Eco Ubuntu” — “I am because we are; we are because the Planet is.” A Dhammācariya who received direct transmission from Venerable Thich Nhat Hanh and was authorised to teach by Jack Kornfield, he serves as the Summit’s Programme Host at Oxford, turning high-level strategy into grounded, participatory leadership.',
    ],
  },
  {
    name: 'Mercedes Martin-Burgess',
    title: 'Founder & CEO, Mercedes Martin & Company',
    role: 'Leading from Wholeness, Oxford · Global Leadership Strategist & IDG Ambassador',
    region: 'Diaspora · Alaska, USA',
    images: [asset('/images/mercedes-martin-burgess.jpg')],
    objectPosition: 'center 15%',
    bio: [
      'Mercedes Martin-Burgess is an award-winning Afro-Latina author, global leadership strategist and IDG Ambassador. As Founder and CEO of Mercedes Martin & Company she stewards The River Journey™ and Leading From Wholeness™, advancing women’s leadership, cultural wisdom and legacy.',
      'A former US Air Force officer and corporate executive, she brings expertise in leadership development, change management, executive coaching and global diversity, and has worked with a client roster that includes Fortune 50 companies. She uses storytelling and metaphor to offer cultural insight to leaders and organisations the world over.',
    ],
  },
  {
    name: 'Ian Mangenga',
    title: 'Founder, Digital Girl Africa',
    role: 'Artificial Intelligence, Oxford · AI Strategy Consultant & Visiting Fellow, LSE',
    region: 'London, United Kingdom',
    images: [],
    bio: [
      'Ian Mangenga is an AI strategy consultant and founder who, over the past decade, has helped culture-shaping organisations — brands, think tanks, cultural institutions and mission-driven bodies — navigate technological change and adopt AI in ways that strengthen innovation while protecting trust, creativity and public value. She is the founder of Digital Girl Africa, an AI lab expanding women’s access to the AI economy through research, advocacy and innovation.',
      'A Visiting Fellow at the London School of Economics, she explores sustainable AI futures in Africa through indigenous knowledge systems, local histories and the continent’s diverse ecologies of intelligence. Her practice bridges strategy, research, design, policy and culture — helping organisations build AI systems that are effective, culturally grounded and designed for long-term public value.',
    ],
  },
  {
    name: 'Dr Irina Fedorenko-Aula',
    title: 'Co-Founder, Flying Forests',
    role: 'Biodiversity & Africa’s Natural Heritage, Oxford · Nature-Based Solutions',
    region: 'Oxford, United Kingdom',
    images: [asset('/images/irina-fedorenko-aula.jpg')],
    bio: [
      'Dr Irina Fedorenko-Aula holds a DPhil from the University of Oxford in Geography and the Environment. She has served as Managing Director of the Caux Dialogue on Environment and Security for the Swiss NGO Initiatives of Change and consulted for the World Bank, specialising in nature-based solutions, climate technology and carbon markets.',
      'A co-founder of BioCarbon Engineering, Vlinder Climate and Flying Forests, she has pioneered the use of technology to restore landscapes at scale, and today works as Head of Origination for Abatable — bringing rigour and imagination to the protection of the natural world.',
    ],
  },
  {
    name: 'Dr Sandile Mtetwa',
    title: 'Climate & Energy Scientist',
    role: 'Climate Resilience, Oxford · PhD in Chemistry, University of Cambridge',
    region: 'Cambridge, United Kingdom',
    images: [],
    bio: [
      'Dr Sandile Mtetwa is a scientist and researcher working at the intersection of science, climate, energy and sustainable development. She holds a PhD in Chemistry from the University of Cambridge, where her research focused on advanced materials for low-carbon energy generation and carbon storage, and has worked with the Centre for Global Equality and Climate Compatible Growth to strengthen research-to-policy collaboration and equitable partnerships between the UK and Kenya.',
      'As a Next Generation Foresight Practitioners Fellow she researches climate and energy futures in Zimbabwe, with a focus on marginalised communities, and is a founding member of the Rondil Scholars Hub. Her work centres on translating scientific knowledge into locally relevant solutions, policy and meaningful community impact.',
    ],
  },
];

export const summit = {
  name: 'African Queens Summit',
  longName: 'African & Diaspora Queens Summit',
  dates: '14 – 31 August 2026',
  cities: ['London', 'Oxford'],
  tagline: 'Inspire · Empower · Unite',
  motto: 'Royalty Defined by Impact',
};

export const venues = [
  {
    id: 'porchester',
    kicker: 'The Ceremonies',
    name: 'Porchester Hall',
    city: 'London · Bayswater',
    image: asset('/images/porchester-1.jpg'),
    description: 'A grand Edwardian hall with soaring ceilings, a gilded ballroom, and capacity for 500 — host to the opening processional, royal receptions, and the closing gala in the heart of London.',
    features: [
      'Historic Edwardian ballroom',
      'Gilded proscenium & chandeliers',
      'Capacity for 500 guests',
      'Central London · Zone 1',
    ],
  },
  {
    id: 'hawkhill',
    kicker: 'The Residence',
    name: 'Hawkhill Place',
    city: 'Oxfordshire',
    image: asset('/images/hawkhill-grounds.png'),
    description: 'An eight-bedroom country retreat set in private gated grounds, with dedicated spa and wellness facilities — the residential home of the queens for the duration of the summit.',
    features: [
      '8 ensuite bedrooms',
      'Private spa & wellness',
      'Walled gardens & gated grounds',
      '45 minutes from London',
    ],
  },
  {
    id: 'oxford',
    kicker: 'The Transformative Leadership Experience',
    name: 'University of Oxford',
    city: 'Oxford',
    image: asset('/images/oxford-colleges.jpg'),
    description: 'A two-day immersive leadership experience at one of the world\'s oldest universities. African Queens, Traditional Leaders, and global changemakers come together to learn, connect, and lead on the forces shaping Africa\'s future — leaving with practical ideas, new partnerships, and a bolder and clearer leadership commitment.',
    features: [
      'Leading Climate Resilience',
      'Protecting Africa\'s Natural Heritage',
      'Leading in the Age of Artificial Intelligence',
      'Leading from Wholeness: The Leadership Africa Needs Next',
    ],
  },
];

export const pillars = [
  {
    name: 'Unity',
    caption: 'One lineage, many crowns',
    body: 'A convocation of queens and first-class kings from across Africa and the Diaspora, gathered in common purpose.',
  },
  {
    name: 'Legacy',
    caption: 'Carrying the flame forward',
    body: 'Honouring the matriarchs who shaped a continent and committing their wisdom to the next generation.',
  },
  {
    name: 'Sovereignty',
    caption: 'The dignity of tradition',
    body: 'Reaffirming the standing of African royalty on the world stage and the integrity of ancestral authority.',
  },
  {
    name: 'Empowerment',
    caption: 'Women leading, communities rising',
    body: 'Advancing women\'s leadership and humanitarian initiatives that reach from the palace to the village.',
  },
];

export const highlights = [
  {
    num: '01',
    title: 'Inspiring Speakers',
    body: 'Keynotes from queens, scholars, and humanitarians whose lives bridge tradition and statecraft.',
  },
  {
    num: '02',
    title: 'Networking Events',
    body: 'Salons, dinners, and private audiences that forge enduring bonds between royal houses and allies.',
  },
  {
    num: '03',
    title: 'Royal Ceremonies',
    body: 'Processions, libations, and honours befitting a convocation of African royalty in the heart of England.',
  },
];

export const matriarchs = [
  {
    name: 'Nefertiti',
    reign: 'c. 1353–1336 BCE',
    region: 'Egypt',
    title: 'Great Royal Wife',
    bio: 'Great Royal Wife of Akhenaten, presiding over one of the wealthiest and most transformative eras of ancient Egypt.',
    image: asset('/images/matriarchs/nefertiti.jpg'),
    artifact: 'Painted limestone bust, Berlin',
  },
  {
    name: 'Hatshepsut',
    reign: 'c. 1479–1458 BCE',
    region: 'Egypt',
    title: 'Pharaoh of Egypt',
    bio: 'One of the most successful pharaohs, a prolific builder who commissioned hundreds of projects and expanded trade.',
    image: asset('/images/matriarchs/hatshepsut.jpg'),
    artifact: 'Limestone seated statue',
  },
  {
    name: 'Makeda',
    reign: '10th century BCE',
    region: 'Ethiopia · Saba',
    title: 'Queen of Sheba',
    bio: 'The legendary queen whose wisdom, wealth, and diplomacy thread through Ethiopian, biblical, and Quranic traditions.',
    image: asset('/images/matriarchs/makeda.jpg'),
    artifact: 'Safavid manuscript painting',
  },
  {
    name: 'Amanirenas',
    reign: 'c. 40–10 BCE',
    region: 'Kush · Nubia',
    title: 'Kandake of Meroë',
    bio: 'The one-eyed warrior queen who led Kushite armies against Rome and negotiated peace with Augustus himself.',
    image: asset('/images/matriarchs/amanirenas.jpg'),
    artifact: '19th c. Lepsius engraving',
  },
  {
    name: 'Amina',
    reign: 'c. 1576–1610',
    region: 'Zazzau · Nigeria',
    title: 'Warrior Queen',
    bio: 'A Hausa warrior queen who expanded her territory through a celebrated military career and mastered the Saharan trade.',
    image: asset('/images/matriarchs/amina.jpg'),
    artifact: 'Equestrian statue, Lagos',
  },
  {
    name: 'Nzinga Mbande',
    reign: '1624–1663',
    region: 'Ndongo · Angola',
    title: 'Queen of Ndongo',
    bio: 'A diplomat and strategist who resisted Portuguese colonisation for four decades, leading armies into her sixties.',
    image: asset('/images/matriarchs/nzinga.jpg'),
    artifact: 'Hand-coloured 19th c. engraving',
  },
  {
    name: 'Yaa Asantewaa',
    reign: '1900',
    region: 'Ashanti · Ghana',
    title: 'Queen Mother of Ejisu',
    bio: 'At sixty, she led the Ashanti in the War of the Golden Stool against the British Empire.',
    image: asset('/images/matriarchs/yaa.jpg'),
    artifact: 'Yaa Asantewaa Museum, Ejisu',
  },
];

export const programme = [
  {
    idx: '01',
    group: 'An Immersive Leadership Experience',
    title: 'The Oxford Leadership Experience',
    body: 'A two-day immersive leadership experience for African Queens, Traditional Leaders, and Global Changemakers at the University of Oxford. Explore the forces shaping Africa\'s future, connect with leaders from across the continent and diaspora, and leave with a personal commitment to lead.',
    image: asset('/images/oxford-colleges.jpg'),
    items: [
      'Learn — global experts on Climate, Biodiversity & AI',
      'Connect — with Queens, Traditional Leaders & Changemakers',
      'Lead — leave with a bolder, clearer leadership commitment',
    ],
  },
  {
    idx: '02',
    group: 'Royal & Cultural',
    title: 'Heritage, Theatre & Immersion',
    body: 'An African theatrical production celebrating heritage and identity, set alongside curated cultural immersion experiences across London.',
    image: asset('/images/queen-aruk-ii-canopy.jpg'),
    items: [
      'African theatrical production',
      'Cultural immersion in London',
      'Heritage exhibitions',
    ],
  },
  {
    idx: '03',
    group: 'Prestige Engagements',
    title: 'Royal Gala, High Tea & Palace',
    body: 'The State Rooms & Royal Mews at Buckingham Palace on 23 August, a prestigious Royal High Tea, and the Royal Gala Night at Porchester Hall in London\'s West End on 25 August — subject to protocol confirmation.',
    image: asset('/images/porchester-2.jpg'),
    items: [
      'Buckingham Palace · State Rooms & Royal Mews · 23 Aug',
      'Royal High Tea at a distinguished London venue',
      'Royal Gala Night · Porchester Hall · 25 Aug',
    ],
  },
  {
    idx: '04',
    group: 'Strategic & Diplomatic',
    title: 'Queens\' Roundtables',
    body: 'High-level Queens\' Roundtables, closed leadership dialogues, and international stakeholder engagements for the royal delegations.',
    image: asset('/images/ipada-diaspora.jpg'),
    items: [
      'High-level Queens\' Roundtables',
      'Closed leadership dialogues',
      'International stakeholder engagements',
    ],
  },
  {
    idx: '05',
    group: 'Cultural Finale',
    title: 'Notting Hill Carnival',
    body: 'Participation in the Notting Hill Carnival on 31 August 2026 — celebrating African and Caribbean cultural excellence on a global stage.',
    image: asset('/images/dancers.jpg'),
    items: [
      'Procession on 31 August 2026',
      'African & Caribbean cultural excellence',
      'Global stage finale',
    ],
  },
  {
    idx: '06',
    group: 'Hospitality',
    title: 'Residence, Transport & Protocol',
    body: 'Luxury accommodation arranged for every attending Queen, with coordinated transport and protocol support throughout the summit.',
    image: asset('/images/hawkhill-grounds.png'),
    items: [
      'Luxury accommodation',
      'Coordinated transport',
      'Protocol support',
    ],
  },
];

export const dignitaries = [
  {
    honorific: 'Her Royal Majesty',
    name: 'Queen Aruk II',
    role: 'Obonganwan of Efik Kingdom',
    region: 'Cross River · Nigeria',
    status: 'Convener',
  },
  {
    honorific: 'Councillor',
    name: 'Chewe Munkonge',
    role: 'The Lord Mayor of Oxford, 2026–27',
    region: 'Oxford · United Kingdom',
    status: 'Confirmed',
  },
  {
    honorific: 'His Imperial Majesty',
    name: 'The Ooni of Ife',
    role: 'Spiritual Head of Yoruba Race',
    region: 'Ile-Ife · Nigeria',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Royal Highness',
    name: 'Princess Namukola',
    role: 'Royal Princess',
    region: 'Zambia',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Royal Highness',
    name: 'Princess Khanyisa Mogale',
    role: 'Princess of the Bapo ba Mogale 2 Kingdom',
    region: 'North West · South Africa',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Royal Majesty',
    name: 'The Queen Mother of Ejisu',
    role: 'Traditional Matriarch of Ashanti',
    region: 'Ashanti Region · Ghana',
    status: 'Invited',
  },
  {
    honorific: 'Her Royal Highness',
    name: 'The Nabagereka of Buganda',
    role: 'Queen Consort of Buganda',
    region: 'Buganda · Uganda',
    status: 'Invited',
  },
  {
    honorific: 'His Royal Majesty',
    name: 'King Silamba of Ndebele',
    role: 'Traditional King of Ndebele',
    region: 'Mpumalanga · South Africa',
    status: 'Confirmed',
  },
  {
    honorific: 'Otunba',
    name: 'Dr Wanle Akinboboye',
    role: 'Founder, Motherland Beckons',
    region: 'Atlanta · Lagos',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Royal Highness',
    name: 'The Queen of Ashanti Diaspora',
    role: 'Ceremonial Head of Diaspora Court',
    region: 'London · Accra',
    status: 'Invited',
  },
  {
    honorific: 'Chief Dr',
    name: 'The Olori of Lagos',
    role: 'Traditional Consort',
    region: 'Lagos · Nigeria',
    status: 'Invited',
  },
  {
    honorific: 'Her Royal Majesty',
    name: 'Queen Diambi Kabatusuila',
    role: 'Queen of the Bakwa Luntu · Luba Kingdom',
    region: 'Kasaï · DR Congo',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Royal Highness',
    name: 'Queen Best Kemigisa',
    role: 'Queen Mother of Tooro Kingdom',
    region: 'Fort Portal · Uganda',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Royal Majesty',
    name: 'Queen Ikamalandel Gumede',
    role: 'Royal Matriarch · Zulu Lineage',
    region: 'South Africa',
    status: 'Confirmed',
  },
  {
    honorific: 'His Majesty',
    name: 'King Guide Bamba',
    role: 'Mansa of Mali · United Kingdoms of Africa',
    region: 'Bamako · Mali',
    status: 'Confirmed',
  },
  {
    honorific: 'His Royal Highness',
    name: 'Olusegun Aderemi',
    role: 'Atayero of Aramoko-Ekiti',
    region: 'Ekiti · Nigeria',
    status: 'Confirmed',
  },
  {
    honorific: 'Ambassador',
    name: 'Jonathan Ojadah',
    role: 'Distinguished Ambassador',
    region: 'Liberia',
    status: 'Confirmed',
  },
  {
    honorific: 'Dr Chief',
    name: 'Amb. Wallace',
    role: 'Distinguished Ambassador',
    region: 'International',
    status: 'Confirmed',
  },
  {
    honorific: 'Ambassador',
    name: 'Coralita Yard',
    role: 'Distinguished Ambassador',
    region: 'Diaspora',
    status: 'Confirmed',
  },
  {
    honorific: 'His Majesty',
    name: 'King Abdirehid Sanwayne',
    role: 'Traditional Sovereign',
    region: 'Somalia',
    status: 'Confirmed',
  },
  {
    honorific: 'His Highness',
    name: 'Omar Ali Hanfare',
    role: 'Distinguished Royal Guest',
    region: 'Djibouti',
    status: 'Confirmed',
  },
  {
    honorific: 'His Royal Highness',
    name: 'Munongo',
    role: 'Traditional Ruler',
    region: 'Kenya',
    status: 'Confirmed',
  },
  {
    honorific: 'His Royal Highness',
    name: 'Prince Iganda Jean Louis Lucien',
    role: 'Guest Speaker · Prince of the Bashinjahavu-Bashaho; President, Movement for the Cultural Renaissance of Africa',
    region: 'DR Congo',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Royal Majesty',
    name: 'Queen Thembi',
    role: 'Royal Matriarch',
    region: 'South Africa',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Royal Highness',
    name: 'Princess Boitumelo',
    role: 'Royal Princess',
    region: 'South Africa',
    status: 'Confirmed',
  },
  {
    honorific: 'His Excellency',
    name: 'Mike Mbuvi Sonko',
    role: 'Former Governor of Nairobi City',
    region: 'Kenya',
    status: 'Confirmed',
  },
  {
    honorific: 'Hon. Dr',
    name: 'Rupa Munugapati',
    role: 'Minister of the Interior',
    region: 'Madagascar',
    status: 'Confirmed',
  },
  {
    honorific: 'Barr.',
    name: 'David Balondemu',
    role: 'Distinguished Guest',
    region: 'Uganda',
    status: 'Confirmed',
  },
  {
    honorific: '',
    name: 'Queen Sanwe',
    role: 'Distinguished Delegate',
    region: 'Zambia',
    status: 'Confirmed',
  },
  {
    honorific: '',
    name: 'Imwiko',
    role: 'Distinguished Delegate',
    region: 'Zambia',
    status: 'Confirmed',
  },
  {
    honorific: 'Ms',
    name: 'Mercy Effiom',
    role: 'Distinguished Delegate',
    region: 'Nigeria',
    status: 'Confirmed',
  },
  {
    honorific: 'Ms',
    name: 'Cecilia Merody',
    role: 'Distinguished Delegate',
    region: 'France',
    status: 'Confirmed',
  },
  {
    honorific: 'Ms',
    name: 'Aida Bluejack',
    role: 'Distinguished Delegate',
    region: 'United Kingdom',
    status: 'Confirmed',
  },
  {
    honorific: '',
    name: 'Tiki Emezie',
    role: 'Distinguished Delegate',
    region: 'United Kingdom',
    status: 'Confirmed',
  },
  {
    honorific: 'Ms',
    name: 'Anita King',
    role: 'Distinguished Delegate',
    region: 'Nigeria',
    status: 'Confirmed',
  },
  {
    honorific: 'Ambassador',
    name: 'Anne Eneita',
    role: 'Distinguished Ambassador',
    region: 'Nigeria',
    status: 'Confirmed',
  },
  {
    honorific: 'Dr',
    name: 'Coby Eneita',
    role: 'Distinguished Delegate',
    region: 'Nigeria',
    status: 'Confirmed',
  },
  {
    honorific: 'Ms',
    name: 'Azadeh Bozorgmanesh-Fard',
    role: 'Distinguished Delegate',
    region: 'Morocco',
    status: 'Confirmed',
  },
  {
    honorific: 'Ms',
    name: 'Aleena Bozorgmanesh-Fard',
    role: 'Distinguished Delegate',
    region: 'Morocco',
    status: 'Confirmed',
  },
  {
    honorific: 'Ms',
    name: 'Samia Maali',
    role: 'Arabic Interpreter · Distinguished Delegate',
    region: 'Morocco',
    status: 'Confirmed',
  },
  {
    honorific: '',
    name: 'Kassim Obsiye',
    role: 'Distinguished Delegate',
    region: 'Somaliland',
    status: 'Confirmed',
  },
  {
    honorific: 'Mr',
    name: 'Mohamed Daw Mabrook Fazzani',
    role: 'Distinguished Delegate',
    region: 'Libya',
    status: 'Confirmed',
  },
  {
    honorific: 'Lady',
    name: 'Chilel Sarr',
    role: 'Distinguished Delegate',
    region: 'The Gambia',
    status: 'Confirmed',
  },
  {
    honorific: 'His Excellency',
    name: 'Senator Prince Bassey Edet Otu, Executive Governor of Cross River State',
    role: 'Government of Cross River State',
    region: 'Cross River · Nigeria',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Excellency',
    name: 'Bishop (Mrs) Eyoanwan Bassey Otu, First Lady of Cross River State',
    role: 'Office of the First Lady, Cross River State',
    region: 'Cross River · Nigeria',
    status: 'Confirmed',
  },
  {
    honorific: 'Mr',
    name: 'Norbert Mbu Mputu',
    role: 'Distinguished Delegate',
    region: 'DR Congo',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Excellency',
    name: 'Epsy Campbell',
    role: 'Former Vice-President of Costa Rica',
    region: 'Costa Rica',
    status: 'Invited',
  },
  {
    honorific: 'Councillor',
    name: 'Dr Dianne Regisford',
    role: 'Oxford City Councillor for Holywell · Founder, Evoking Belonging',
    region: 'Diaspora · United Kingdom',
    status: 'Confirmed',
  },
  {
    honorific: 'His Majesty',
    name: 'Ali Ibrahim',
    role: 'The Sekyere South Municipal Zongo King',
    region: 'Ashanti · Ghana',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Royal Majesty',
    name: 'Nana Akrofoso',
    role: 'Queen Mother of Bedomasi',
    region: 'Ashanti · Ghana',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Royal Majesty',
    name: 'Nana Akrofoso Hemaa',
    role: 'Queen Mother of Akrofoso',
    region: 'Ashanti · Ghana',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Royal Highness',
    name: 'Princess Moloto Exley',
    role: 'Royal Princess',
    region: 'South Africa',
    status: 'Confirmed',
  },
  {
    honorific: '',
    name: 'Nana Kerzia Manu',
    role: 'Distinguished Delegate',
    region: 'Ghana',
    status: 'Confirmed',
  },
  {
    honorific: 'His Royal Highness',
    name: 'Prince Ziaudeen Ibrahim',
    role: 'Royal Prince',
    region: 'Ashanti · Ghana',
    status: 'Confirmed',
  },
  {
    honorific: 'Ms',
    name: 'Kate Badu',
    role: 'Distinguished Delegate',
    region: 'Ghana',
    status: 'Confirmed',
  },
  {
    honorific: 'Her Royal Highness',
    name: 'Queen Consort Maangela Imwiko',
    role: 'Barotse Royal Establishment · Mwandi Palace',
    region: 'Western Province · Zambia',
    status: 'Confirmed',
  },
  {
    honorific: '',
    name: 'Tolou',
    role: 'Entertainer & Singer',
    region: '',
    status: 'Confirmed',
  },
  {
    honorific: 'Mr',
    name: 'Michael Okoigun',
    role: 'Distinguished Delegate',
    region: '',
    status: 'Confirmed',
  },
  {
    honorific: '',
    name: 'Gessele Angba Rhima',
    role: 'Distinguished Delegate',
    region: '',
    status: 'Confirmed',
  },
  {
    honorific: 'Mr',
    name: 'Lucas Odell Angba',
    role: 'Distinguished Delegate',
    region: '',
    status: 'Confirmed',
  },
  {
    honorific: 'Dr',
    name: 'Elizabeth Kangethe',
    role: 'Vice-President, London Mayors Association · Past Mayor & Councillor, Barking and Dagenham',
    region: 'London · United Kingdom',
    status: 'Confirmed',
  },
];

// Four registration packages. Each includes the three flagship engagements.
// `retail` is the indicative à-la-carte value, shown struck through to convey
// the saving against the summit package rate.
export const packages = [
  { name: 'African Queens Summit Bronze', price: 400, retail: 600, note: 'The three flagship engagements', body: 'Oxford, the Royal Gala and Buckingham Palace — the heart of the summit.', image: asset('/images/oxford-university.jpg'), stripe: 'https://buy.stripe.com/test_00w9ATfdCdJV8Cl4rQ8og01' },
  { name: 'African Queens Summit Silver', price: 480, retail: 760, note: 'Flagships + any two excursions', body: 'Add two further outings of your choosing from the programme.', image: asset('/images/oxford-magdalen.jpg'), stripe: 'https://buy.stripe.com/test_7sY8wP3uU7lx6ud4rQ8og03' },
  { name: 'African Queens Summit Gold', price: 550, retail: 920, note: 'Flagships + any three excursions', body: 'Add three further outings of your choosing from the programme.', featured: true, image: asset('/images/dancers.jpg'), stripe: 'https://buy.stripe.com/test_eVq9AT9TiaxJ3i1bUi8og02' },
  { name: 'African Queens Summit Platinum', price: 650, retail: 1100, note: 'Any available engagement', body: 'The complete convocation — any available excursion across the seventeen days.', premium: true, image: asset('/images/queen-aruk-ii-throne.jpg'), stripe: 'https://checkout.africanqueenssummit.com/b/4gM8wPe9H0bu4pj6Vj1VK0d' },
];

// The day-by-day programme. `price` is a number (GBP) or a label / null.
// `image` is set where a real photograph exists; cards without one fall back
// to a branded placeholder.
// `price` is the summit (conference) rate paid by attendees; `retail` is the
// indicative individual / on-the-door value, shown struck through to make the
// saving visible.
export const itinerary = [
  { date: '14–15 Aug', title: 'Arrival & Welcome', price: null, image: asset('/images/queen-aruk-ii-throne.jpg'), detail: 'Reception of the royal delegations and settling into residence.' },
  { date: '16 Aug', title: 'Opening Ceremony', price: 'Included', image: asset('/images/porchester-1.jpg'), detail: 'The grand opening processional and royal reception.' },
  { date: '17–18 Aug', title: 'Oxford University', price: 150, retail: 220, flagship: true, image: asset('/images/oxford-university.jpg'), detail: 'The two-day Transformative Leadership Experience at Oxford — learn, connect and lead on the forces shaping Africa\'s future.', checkout: 'https://checkout.africanqueenssummit.com/b/4gMcN5fdLaQ81d75Rf1VK07' },
  { date: '19 Aug', title: 'Blenheim Palace', price: 72, image: asset('/images/blenheim-palace.jpg'), detail: 'A private visit to the birthplace of Sir Winston Churchill.', checkout: 'https://checkout.africanqueenssummit.com/b/28E14n9Tr0bu1d73J71VK0l' },
  { date: '20 Aug', title: "Lord Mayor's Reception", price: 40, retail: 60, image: asset('/images/lord-mayor.jpg'), detail: 'A civic reception in the historic City of London.', checkout: 'https://checkout.africanqueenssummit.com/b/dRm4gzc1ze2kdZT7Zn1VK0g' },
  { date: '21 Aug', title: 'Bicester Village', price: 75, image: asset('/images/bicester-village.jpg'), detail: 'A luxury shopping excursion — lunch included.', checkout: 'https://checkout.africanqueenssummit.com/b/5kQ3cv4z79M49JD5Rf1VK0c' },
  { date: '22 Aug', title: 'Rest, Art & Leisure', price: 20, retail: 30, image: asset('/images/hawkhill-grounds.png'), detail: 'A restful day at Hawkhill with art, spa and wellness.', checkout: 'https://checkout.africanqueenssummit.com/b/7sYbJ15DbaQ8g81enL1VK0m' },
  { date: '23 Aug', title: 'Buckingham Palace', price: 100, retail: 140, flagship: true, image: asset('/images/buckingham-palace.jpg'), detail: 'The State Rooms & Royal Mews, subject to protocol confirmation.', checkout: 'https://checkout.africanqueenssummit.com/b/fZu8wP1mV0bucVPgvT1VK0k' },
  { date: '24 Aug', title: 'London Sightseeing & River Cruise', price: 65, image: asset('/images/london-sightseeing.jpg'), detail: 'A guided open-top coach tour of the capital with a Thames river cruise — a 24-hour pass.' },
  { date: '25 Aug', title: 'Royal Gala Night', price: 150, retail: 220, flagship: true, image: asset('/images/porchester-2.jpg'), detail: 'The black-tie Gala at Porchester Hall, London.', checkout: 'https://checkout.africanqueenssummit.com/b/00w00j8Pn0bu6xr0wV1VK0a' },
  { date: '26 Aug', title: 'Kew Gardens', price: 'Free', image: asset('/images/kew-gardens.jpg'), detail: 'The Royal Botanic Gardens at Kew — no entrance fee.' },
  { date: '27 Aug', title: "St Paul's & Tower of London", price: 100, image: asset('/images/st-pauls.jpg'), detail: 'The cathedral, the Tower and the Crown Jewels.', checkout: 'https://checkout.africanqueenssummit.com/b/cNi3cvd5Dgas9JD1AZ1VK0o' },
  { date: '28 Aug', title: 'Westminster Abbey', price: 55, image: asset('/images/westminster.jpg'), detail: 'A visit to the historic Westminster Abbey.', checkout: 'https://checkout.africanqueenssummit.com/b/6oUaEXfdL8I07Bv4Nb1VK0r' },
  { date: '29–30 Aug', title: 'Rest', price: 'Free', image: asset('/images/london-rest.jpg'), detail: 'Leisure days and personal engagements.' },
  { date: '31 Aug', title: 'Notting Hill Carnival', price: 'Free', image: asset('/images/celebration-carnival.jpg'), detail: 'The cultural finale on a global stage.' },
];

// Programme Highlights — the ceremonial day-by-day overview, mirrored from the
// official invitation letter (date, engagement, icon).
export const programmeHighlights = [
  { date: '14–15 Aug', title: 'Royal Arrival & Protocol Reception', icon: '👑' },
  { date: '16 Aug', title: 'Opening of the Summit', icon: '📜' },
  { date: '17–18 Aug', title: 'Transformative Leadership Experience at Oxford', icon: '🎓' },
  { date: '19 Aug', title: 'Visit to Blenheim Palace', icon: '🏰' },
  { date: '20 Aug', title: 'Courtesy visit to the Lord Mayor of Oxford · Art Exhibition', icon: '🎨' },
  { date: '21 Aug', title: 'Bicester Designer Village', icon: '🛍️' },
  { date: '22 Aug', title: "Day of Rest · Queen's Strategic Roundtables (closed-door)", icon: '🫖' },
  { date: '23 Aug', title: 'Buckingham State Rooms & Royal Mews', icon: '🏛️' },
  { date: '24 Aug', title: 'London bus tour — Big Ben, London Eye', icon: '🎡' },
  { date: '25 Aug', title: 'Gala Night — Fashion, Art & Entertainment · Porchester Hall', icon: '🥂' },
  { date: '26 Aug', title: 'Kew Gardens', icon: '🌿' },
  { date: '27 Aug', title: "St Paul's Cathedral & Tower of London", icon: '🗼' },
  { date: '28 Aug', title: 'Westminster Abbey', icon: '⛪' },
  { date: '29–30 Aug', title: 'Free', icon: '🕊️' },
  { date: '31 Aug', title: 'Notting Hill Carnival — End of Summit', icon: '🥳' },
];

// Optional London attractions, bookable as add-ons. Per person.
export const extras = [
  { name: 'London Eye', price: '£33' },
  { name: 'Madame Tussauds', price: '£51' },
  { name: 'Thames River Cruise', price: '£18' },
];

export const tiers = [
  {
    name: 'Observer',
    price: '£50',
    tag: 'Entry pass',
    body: 'Access to public convocations, exhibitions, and the opening processional. Ideal for scholars, press, and supporters.',
    includes: [
      'Opening processional · 14 Aug',
      'Cultural heritage exhibition',
      'One plenary keynote',
      'Closing cultural performance',
    ],
    featured: false,
  },
  {
    name: 'Royal Guest',
    price: '£200',
    tag: 'Full programme',
    body: 'Full access to the summit programme — ceremonies, forums, the Transformative Leadership Experience at Oxford, and the closing gala at Porchester Hall.',
    includes: [
      'All Observer benefits',
      'Leadership forum & panels',
      'Transformative Leadership Experience at Oxford',
      'Honorary banquet · Oxford',
      'Closing gala · Porchester Hall',
    ],
    featured: true,
  },
  {
    name: 'Patron',
    price: '£500',
    tag: 'Residence included',
    body: 'The complete convocation with residence at Hawkhill Place, private audiences, and patronage recognition in the official programme.',
    includes: [
      'All Royal Guest benefits',
      'Residence at Hawkhill Place',
      'Spa & wellness access',
      'Private royal audience',
      'Patronage in the programme',
    ],
    featured: false,
  },
];

export const partners = [
  { name: 'Queen Aruk II Foundation', role: 'Convener' },
  { name: 'IPADA Initiatives', role: 'Principal Partner', featured: true },
  { name: 'Forum of African Traditional Authorities', role: 'Institutional Partner' },
  { name: 'Maasai Tourism Festival', role: 'Cultural Partner' },
  { name: 'Motherland Beckons', role: 'Diaspora Partner' },
  { name: 'Foundation of African Royals', role: 'Royal Partner' },
  { name: 'United International Peace & Governance Council', role: 'International Partner' },
  { name: 'One Thriving Planet', role: 'Global Partner' },
];

// Confirmed delegates — participants who have registered and confirmed their
// attendance at the African Queens Summit 2026.
export const delegates = [
  'Florence Tigah', 'Stephen Addo', 'Abu Bonsrah Daniel', 'Martha Anyopoka',
  'Deborah Larbi', 'Cephas Asakia', 'Valis Ofori', 'Acheampong Theresah',
  'Owusu Erica Diamond', 'Awuni George', 'Cecilia Vincentia Corleki Adjaottor',
  'Michael Cobbina', 'Menen Oparebea Larbi', 'Ruth Nyarko', 'Prince Appiah',
  'Gloria Sarkodie', 'Stephen Akowuah', 'Stephen K. Nutsugah', 'Felix Akiti',
  'Stephanie Adwoa Frimpong', 'Mercy Ante Agyepong', 'Yvonne Owusu',
  'Daniel Quansah', 'Sarah Hammond', 'Felix Korang Ntiamoah',
  'Christopher Kyei Agyapong', 'Georgina Mawutordzi', 'Agartha Yeboah',
  'Arnold Tetteh Mensah', 'Ebenezer Kingsley Kofi Afful', 'Naomi Dansoa Amoah',
  'Prince Awulosu', 'Sharon Nanjala née Sandwe', 'Theresa Pellser Nakubiana',
];
